/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { LEGAL_ADDRESS } from "@/shared/lib/company-addresses";

const CHROME_STYLES = `
.integration-chrome{--accent:#D4531A;--accent-light:#FCE9DF;--accent-dark:#A23E12;--ink:#14151A;--text-secondary:#595B66;--border:#E6E8EE;font-family:var(--font-jakarta,'Plus Jakarta Sans',system-ui,-apple-system,sans-serif)}
.integration-chrome *{box-sizing:border-box}.integration-chrome .container{max-width:1180px;margin:0 auto;padding:0 24px}
.integration-chrome .nav{position:sticky;top:0;z-index:50;background:rgba(255,255,255,.86);backdrop-filter:blur(12px);border-bottom:1px solid var(--border)}
.integration-chrome .nav-inner{max-width:1180px;margin:0 auto;padding:0 24px;height:64px;display:flex;align-items:center;justify-content:space-between;gap:20px}.integration-chrome .logo{display:inline-flex}.integration-chrome .navlinks{display:flex;align-items:center;gap:28px}.integration-chrome .navlinks a{font-size:14px;font-weight:600;color:var(--text-secondary);text-decoration:none}.integration-chrome .navlinks a:hover{color:var(--ink)}.integration-chrome .nav-btns{display:flex;align-items:center;gap:10px}.integration-chrome .nav-ghost{font-size:14px;font-weight:700;color:var(--accent);text-decoration:none;padding:9px 14px;border:1px solid var(--accent-light);border-radius:8px;white-space:nowrap}.integration-chrome .nav-ghost:hover{background:var(--accent-light)}.integration-chrome .nav-cta{background:var(--accent);color:#fff;font-size:14px;font-weight:700;padding:9px 16px;border-radius:8px;text-decoration:none;white-space:nowrap}.integration-chrome .nav-cta:hover{background:var(--accent-dark)}
.integration-chrome .integration-footer{background:var(--ink);color:#B9C0C9;padding:52px 0 30px}.integration-chrome .foot-grid{display:grid;grid-template-columns:1.6fr 1fr 1fr 1fr;gap:32px}.integration-chrome .integration-footer .ftag{margin-top:12px;font-size:13.5px;line-height:1.6;max-width:280px}.integration-chrome .integration-footer .faddr{margin-top:14px;font-size:12px;color:#8A929C;line-height:1.5}.integration-chrome .integration-footer h4{font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#8A929C;margin:0 0 14px}.integration-chrome .integration-footer ul{display:flex;flex-direction:column;gap:9px;list-style:none;margin:0;padding:0}.integration-chrome .integration-footer ul a{font-size:13.5px;color:#B9C0C9;text-decoration:none}.integration-chrome .integration-footer ul a:hover{color:#fff}.integration-chrome .foot-bottom{margin-top:40px;padding-top:22px;border-top:1px solid rgba(255,255,255,.1);display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;font-size:12.5px;color:#8A929C}@media(max-width:760px){.integration-chrome .navlinks,.integration-chrome .nav-ghost{display:none}.integration-chrome .foot-grid{grid-template-columns:1fr 1fr;gap:28px}}
`;

export function IntegrationSiteHeader() {
  return <div className="integration-chrome"><style>{CHROME_STYLES}</style><nav className="nav"><div className="nav-inner"><Link href="/" className="logo"><img src="/getbackplate-logo-light.svg" alt="GetBackplate" style={{ height: 28, width: "auto", display: "block" }} /></Link><div className="navlinks"><Link href="/platform">Platform</Link><Link href="/integrations/qbo-r365#integrations">Integration</Link><Link href="/integrations/qbo-r365#proof">Case study</Link><Link href="/integrations/qbo-r365#pricing">Pricing</Link><Link href="/integrations/qbo-r365#faq">FAQ</Link></div><div className="nav-btns"><Link href="/refer" className="nav-ghost">Refer a vendor</Link><Link className="nav-cta" href="/integrations/qbo-r365#pricing">Start sending →</Link></div></div></nav></div>;
}

export function IntegrationSiteFooter() {
  return <div className="integration-chrome"><footer className="integration-footer"><div className="container"><div className="foot-grid"><div><img src="/getbackplate-logo-footer.svg" alt="GetBackplate" style={{ height: 22, width: "auto" }} /><div className="ftag">Automated invoice delivery from QuickBooks® Online into your customers&apos; Restaurant365 — built for food vendors and distributors.</div><div className="faddr">{LEGAL_ADDRESS.line1}<br />{LEGAL_ADDRESS.cityStatePostal}</div></div><div><h4>Product</h4><ul><li><Link href="/integrations/qbo-r365#integrations">Integration</Link></li><li><Link href="/integrations/qbo-r365#pricing">Pricing</Link></li><li><Link href="/integrations/qbo-r365#proof">Case study</Link></li><li><Link href="/integrations/qbo-r365#faq">FAQ</Link></li></ul></div><div><h4><Link href="/legal">Legal</Link></h4><ul><li><Link href="/legal/integration/privacy">Privacy</Link></li><li><Link href="/legal/integration/terms">Terms</Link></li><li><Link href="/legal/integration/msa">MSA</Link></li><li><Link href="/legal/integration/incident-response">Incident Response</Link></li></ul></div><div><h4>Company</h4><ul><li><Link href="/trust">Trust Center</Link></li><li><Link href="/refer">Refer a vendor</Link></li><li><a href="mailto:hello@getbackplate.com">Contact</a></li><li><a href="https://app.getbackplate.com">Login</a></li></ul></div></div><div className="foot-bottom"><span>© 2026 Backplate Technologies LLC. All rights reserved.</span><span>hello@getbackplate.com</span></div></div></footer></div>;
}
